/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package Vista;

/**
 *
 * @author Eduardo Varela
 */
public class RazonesMercado extends javax.swing.JFrame {

    /**
     * Creates new form RazonesMercado
     */
    public RazonesMercado() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        tfDenUtilidad = new javax.swing.JTextField();
        tfNumUtilidad = new javax.swing.JTextField();
        tfDenRazon = new javax.swing.JTextField();
        tfNumRazon = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        jSeparator3 = new javax.swing.JSeparator();
        jLabel4 = new javax.swing.JLabel();
        lblResultUtil = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        lblResultRazon = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Razones de Mercado");
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jPanel1.setBackground(new java.awt.Color(66, 57, 58));
        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Razones de Mercado");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(139, 6, -1, -1));

        jLabel2.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("Utilidad por acción: ");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(45, 128, -1, -1));

        jLabel3.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Razón precio/unidades:");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(46, 270, -1, -1));

        tfDenUtilidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfDenUtilidad.setForeground(new java.awt.Color(255, 255, 255));
        tfDenUtilidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenUtilidad.setBorder(null);
        tfDenUtilidad.setOpaque(false);
        tfDenUtilidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfDenUtilidadActionPerformed(evt);
            }
        });
        jPanel1.add(tfDenUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 140, 102, -1));

        tfNumUtilidad.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfNumUtilidad.setForeground(new java.awt.Color(255, 255, 255));
        tfNumUtilidad.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumUtilidad.setBorder(null);
        tfNumUtilidad.setOpaque(false);
        jPanel1.add(tfNumUtilidad, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 106, 102, -1));

        tfDenRazon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfDenRazon.setForeground(new java.awt.Color(255, 255, 255));
        tfDenRazon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfDenRazon.setBorder(null);
        tfDenRazon.setOpaque(false);
        jPanel1.add(tfDenRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 282, 102, -1));

        tfNumRazon.setFont(new java.awt.Font("Segoe UI", 0, 16)); // NOI18N
        tfNumRazon.setForeground(new java.awt.Color(255, 255, 255));
        tfNumRazon.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        tfNumRazon.setBorder(null);
        tfNumRazon.setOpaque(false);
        tfNumRazon.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                tfNumRazonActionPerformed(evt);
            }
        });
        jPanel1.add(tfNumRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 246, 102, -1));

        jSeparator2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 274, 102, -1));

        jSeparator3.setBackground(new java.awt.Color(255, 255, 255));
        jPanel1.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(238, 134, 102, -1));

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("=");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 122, -1, -1));

        lblResultUtil.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblResultUtil.setForeground(new java.awt.Color(255, 255, 255));
        lblResultUtil.setText("0.0");
        jPanel1.add(lblResultUtil, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 122, -1, -1));

        jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("=");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(366, 262, -1, -1));

        lblResultRazon.setFont(new java.awt.Font("Segoe UI", 1, 16)); // NOI18N
        lblResultRazon.setForeground(new java.awt.Color(255, 255, 255));
        lblResultRazon.setText("0.0");
        jPanel1.add(lblResultRazon, new org.netbeans.lib.awtextra.AbsoluteConstraints(395, 262, -1, -1));

        getContentPane().add(jPanel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 510, 380));

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tfDenUtilidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfDenUtilidadActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfDenUtilidadActionPerformed

    private void tfNumRazonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_tfNumRazonActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_tfNumRazonActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(RazonesMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(RazonesMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(RazonesMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(RazonesMercado.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new RazonesMercado().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    public javax.swing.JLabel lblResultRazon;
    public javax.swing.JLabel lblResultUtil;
    public javax.swing.JTextField tfDenRazon;
    public javax.swing.JTextField tfDenUtilidad;
    public javax.swing.JTextField tfNumRazon;
    public javax.swing.JTextField tfNumUtilidad;
    // End of variables declaration//GEN-END:variables
}
